<img class="logo" src="assets/images/logo.png" />
		
<div class="formulario">
    <p class="titulo text-center">Políticas</p>
    <div class="container_legales">
    <p><strong>AVISO DE PRIVACIDAD</strong></p>
<p>&nbsp;</p>
<p><strong>&iquest;Qui&eacute;n ser&aacute; el responsable de sus datos personales? </strong></p>
<p><strong>PEOPLE INCORPORATED S.A DE C.V</strong>, con nombre comercial &ldquo;CATORCE DIAS&rdquo;, con domicilio en: Damas #129 Colonia San Jos&eacute; Insurgentes, Benito Ju&aacute;rez, Ciudad de M&eacute;xico, C.P. 03900; es responsable del tratamiento de los datos personales recabados en la promoci&oacute;n denominada <strong>&ldquo;</strong>Con Tang&reg; quiero m&aacute;s<strong>&rdquo;</strong>, en t&eacute;rminos de la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de los Particulares.</p>
<p>Los datos personales obtenidos directamente o a trav&eacute;s de medios electr&oacute;nicos ser&aacute;n tratados por&nbsp;<strong>&ldquo;PEOPLE INCORPORATED S.A DE C.V.</strong>, con nombre comercial &ldquo;CATORCE DIAS&rdquo;, bajo los principios de licitud, consentimiento, informaci&oacute;n, calidad, finalidad, lealtad, proporcionalidad y responsabilidad, de conformidad con lo dispuesto por la Ley.</p>
<p>Los datos personales proporcionados a&nbsp;<strong>PEOPLE INCORPORATED S.A DE C.V.</strong>, con nombre comercial &ldquo;CATORCE DIAS&rdquo;, se encontrar&aacute;n debidamente protegidos a trav&eacute;s de medidas de seguridad, tecnol&oacute;gicas, f&iacute;sicas y administrativas, previniendo el uso o divulgaci&oacute;n indebida de los mismos.</p>
<p><strong>&iquest;Qu&eacute; datos personales se recabaran? </strong></p>
<p>Los datos personales que proporcionar&aacute; al responsable, ser&aacute;n su (nombre completo, correo electr&oacute;nico, tel&eacute;fono, domicilio, RFC y correo electr&oacute;nico (e-mail)&nbsp;</p>
<p><strong>&iquest;Con que fines recabaremos y usaremos sus datos personales? </strong></p>
<p>La recolecci&oacute;n y uso de sus datos personales tendr&aacute; relaci&oacute;n directa con la participaci&oacute;n en la promoci&oacute;n denominada <strong>&ldquo;</strong>Con Tang&reg; quiero m&aacute;s, mucho m&aacute;s&rdquo; (Digital) por tal motivo el &uacute;nico uso que le daremos a los datos ser&aacute;: Identificar al acreedor de los incentivos ofrecidos, realizar el proceso de validaci&oacute;n para declararlo y registrarlo como ganador, y realizar la entrega del premio con base en los t&eacute;rminos de las presentes condiciones.</p>
<p><strong>&iquest;Transferir&aacute;n mis datos personales alg&uacute;n tercero? </strong></p>
<p>Para el caso de que el responsable requiera transferir sus datos personales a un tercero, primero le solicitara autorizaci&oacute;n previa inform&aacute;ndole los datos que permitan identificar al tercero al cual se pretenden transferir sus datos , as&iacute; como, el domicilio , los usos que se pretenda dar a su informaci&oacute;n, desde luego nos abstendremos de hacer dicha transferencia para el caso de que usted no lo autorice, en el entendido de que tal esquema de transferencia de &ldquo;datos personales&rdquo; se encuentra sujeto a lo establecido por las fracciones iii y iv del art&iacute;culo 37 de la ley federal para la protecci&oacute;n de datos personales en posesi&oacute;n de los particulares, en lo sucesivo la &ldquo;ley&rdquo;.</p>
<p><strong>&iquest;C&oacute;mo puedo manifestar mi negativa para el tratamiento de mis datos personales? </strong></p>
<p>Si usted no est&aacute; de acuerdo con el usos de sus datos personales &ldquo;datos personales&rdquo;, le solicitamos nos manifieste su negativa al respecto, a trav&eacute;s de los medios que m&aacute;s adelante se mencionan para hacer valer sus <strong>derechos ARCO</strong>, en donde en un t&eacute;rmino de diez d&iacute;as h&aacute;biles contados a partir de que se reciba dicha solicitud de negativa se le confirmar&aacute; la recepci&oacute;n del mismo y nos abstendremos del manejo de los &ldquo;datos personales&rdquo; en los t&eacute;rminos restringidos por su titular.</p>
<p>La temporalidad del manejo de los datos personales ser&iacute;a hasta en tanto usted nos manifieste la decisi&oacute;n de que sus datos sean eliminados y hasta en tanto se cumpla con la finalidad para la que fueron proporcionados, desde luego usted podr&aacute; oponerse en cualquier momento que lo considere oportuno. Una vez que los datos personales hayan sido utilizados para los fines mencionados anteriormente, se proceder&aacute; a su cancelaci&oacute;n y bloqueo, conserv&aacute;ndolos solo para su resguardo por un plazo no mayor a 5 a&ntilde;os contados a partir del uso efectivo de los mismos, en atenci&oacute;n al plazo con el que cuentan las autoridades para ejercer sus facultades de verificaci&oacute;n y vigilancia, procediendo posteriormente a la destrucci&oacute;n y/o supresi&oacute;n de sus datos personales siempre y cuando no exista requerimiento alguno por parte de autoridad competente, situaci&oacute;n que en su caso interrumpir&iacute;a el plazo de destrucci&oacute;n referido.</p>
<p><strong>&iquest;C&oacute;mo proteger&aacute;n y tratar&aacute;n mis datos personales? </strong></p>
<p>Una vez que usted entregue al responsable sus datos personales, le manifestamos que estos ser&aacute;n conservados en diferentes medios seguros que la tecnolog&iacute;a permita, cuyo acceso estar&aacute; limitado solamente a las personas f&iacute;sicas que colaboran con la responsable o con los proveedores encargados de la informaci&oacute;n y/o personas morales con la que el responsable tenga alguna relaci&oacute;n jur&iacute;dica y cuya autorizaci&oacute;n usted previamente hubiere concedido. El responsable contar&aacute; con las medidas de seguridad que considere adecuadas para proteger el uso de sus datos personales por parte de terceros no autorizados y respecto de las cuales usted podr&aacute; requerir informaci&oacute;n en cualquier momento que lo considere oportuno, sin embargo, en caso de alguna vulneraci&oacute;n se lo haremos saber as&iacute; como las medidas tomadas para denunciar, coadyuvar en las labores de investigaci&oacute;n y prevenir cualquier mal manejo de la informaci&oacute;n. En caso de requerimiento de alguna autoridad, los datos personales podr&aacute;n ponerse a disposici&oacute;n de &eacute;stas, dentro del estricto cumplimiento a la ley.</p>
<p><strong>Autorizaci&oacute;n para el tratamiento de mis datos personales </strong></p>
<p>El tratamiento de sus datos personales, que se han puesto a disposici&oacute;n del responsable bajo cualquier forma o circunstancia, podr&aacute; ser efectuado por el responsable de conformidad con los presentes t&eacute;rminos y condiciones, por lo que desde este momento se entiende que usted autoriza expresamente al responsable para tal efecto, hasta en tanto usted manifieste su oposici&oacute;n mediante alguno de los medios que indica la ley.</p>
<p><strong>&iquest;Cu&aacute;les son los medios y procedimientos para ejercer los derechos ARCO? </strong></p>
<p>Conforme a la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de Particulares, son los derechos que toda persona puede ejercer en relaci&oacute;n con el tratamiento de sus datos personales. Cada sigla representa un derecho diferente y son Acceso, Rectificaci&oacute;n, Cancelaci&oacute;n y Oposici&oacute;n.</p>
<p>Usted puede dejar de recibir mensajes promocionales por tel&eacute;fono fijo o celular, asimismo, puede dejar de recibir correo postal publicitario, tambi&eacute;n puede dejar de recibir correos electr&oacute;nicos con promocionales.</p>
<p>Usted tiene derecho a acceder a sus datos personales que poseemos y a los detalles del tratamiento de los mismos, as&iacute; como a rectificarlos en caso de ser inexactos o incompletos; cancelarlos cuando considere que no se requieren para alguna de las finalidades se&ntilde;alados en el presente aviso de privacidad, est&eacute;n siendo utilizados para finalidades no consentidas o haya finalizado la relaci&oacute;n contractual o de servicio, o bien, oponerse al tratamiento de los mismos para fines espec&iacute;ficos.</p>
<p>Usted podr&aacute; en cualquier momento revocar el consentimiento que ha otorgado a &ldquo;CATORCE DIAS&rdquo;, para el tratamiento de sus datos personales, limitar el uso o divulgaci&oacute;n de los mismos y ejercer sus Derechos ARCO previstos en la Ley, para ello, es necesario que realice su petici&oacute;n en la direcci&oacute;n electr&oacute;nica que proporcionamos y en un plazo m&aacute;ximo de 60 d&iacute;as atenderemos su petici&oacute;n y le informaremos sobre la procedencia de la misma a trav&eacute;s de un mensaje de correo electr&oacute;nico o el medio que nos indique</p>
<p><strong>Modificaciones al aviso de privacidad</strong></p>
<p>Nos reservamos el derecho de efectuar en cualquier momento modificaciones o actualizaciones al presente aviso de privacidad, para la atenci&oacute;n de novedades legislativas, pol&iacute;ticas internas o nuevos requerimientos para la prestaci&oacute;n u ofrecimiento de nuestros servicios o productos. Las modificaciones estar&aacute;n disponibles al p&uacute;blico mediante: (i) anuncios visibles en nuestros establecimientos o centros de atenci&oacute;n a clientes; (ii) tr&iacute;pticos o folletos disponibles en nuestros establecimientos o centros de atenci&oacute;n a clientes; (iii) en nuestra p&aacute;gina de Internet [secci&oacute;n aviso de privacidad]; (iv) o se las haremos llegar al &uacute;ltimo correo electr&oacute;nico que nos haya proporcionado.</p>
<p><strong>&iquest;Ante qui&eacute;n puede presentar sus quejas y denuncias por el tratamiento indebido de sus datos personales?</strong></p>
<p>Si usted considera que su derecho de protecci&oacute;n de datos personales ha sido lesionado por alguna conducta de nuestros empleados o de nuestras actuaciones o respuestas, presume que en el tratamiento de sus datos personales existe alguna violaci&oacute;n a las disposiciones previstas en la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de los Particulares, podr&aacute;́ interponer la queja o denuncia correspondiente ante el INAI (Instituto Nacional de Transparencia, Acceso a la Informaci&oacute;n y Protecci&oacute;n de Datos Personales), para mayor informaci&oacute;n visite www.inai.org.mx .</p>
<p><strong>Responsable de la Privacidad de los Datos</strong></p>
<p>Si tiene alguna duda, pregunta o queja, puede comunicarse con nuestro departamento de atenci&oacute;n al cliente, nuestro n&uacute;mero de tel&eacute;fono es 5286-6095&nbsp;y podemos ayudarle en un horario de 10:00 a 18:00 horas de lunes a viernes. Ponemos a su disposici&oacute;n nuestra direcci&oacute;n electr&oacute;nica (<a href="about:blank">informaci&oacute;n@catorcedias.com</a>), todas sus preguntas ser&aacute;n respondidas.</p>
<p><strong>Transferencia de datos a un tercero llamado &ldquo;MONDELEZ M&Eacute;XICO&rdquo;, S. DE R.L. DE C.V.&rdquo; durante y al finalizar la vigencia de la promoci&oacute;n &ldquo;</strong>Con Tang&reg; quiero m&aacute;s <strong>para cumplir con las Bases de la misma.</strong></p>
<p>El otorgante manifiesta su consentimiento para que durante la vigencia y al t&eacute;rmino de la promoci&oacute;n, sus datos personales proporcionados ser&aacute;n compartidos a <strong>&ldquo;MONDELEZ M&Eacute;XICO&rdquo;, S. DE R.L. DE C.V.&rdquo; </strong>quien ser&aacute; responsable de los mismos en los mismos t&eacute;rminos y alcances jur&iacute;dicos que manifestados en el presente aviso de privacidad.</p>
<p>&nbsp;</p>
<p>&nbsp;</p> 
    </div>
</div>